# Project
version=1.0.0
group=xyz.reycko
java_version=21

# Common
minecraft_version=1.20.6
mod_name=LetMeSymlink
mod_author=Reycko
mod_id=letmesymlink
license=LGPL-3.0
credits=
description=Removes the annoying feature from 1.20.6+ that prevents resource packs to be contained in a symbolic link.
minecraft_version_range=[1.20.6, 1.21]

# Neoform
neo_form_version=1.20.6-20240627.102356

# Loom
loom_version=1.7-SNAPSHOT

# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.20.6
parchment_version=2024.06.16

# Fabric
fabric_loader_version=0.15.0

# Forge
forgegradle_version=[6.0,7.0)
forge_version=50.2.10
forge_loader_version_range=[50,61]

# NeoForge
neoforge_version=20.6.136
neoforge_loader_version_range=[4,)
neoforge_mdg_version=0.1.131

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
